廃止されたException.messageを修正
Exception.message、Python 2.6では非推奨になり、Python3では削除されました。
// Error: AttributeError: file SIWeightEditor\Contents\scripts\siweighteditor\store_skin_weight_om2.py line 94: 'RuntimeError' object has no attribute 'message' //

(cherry picked from commit a9524f8d1e903bea5112e2419c9dc09445cb2087)